apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:
    my-db
spec:
  serviceName: my-db-service
  replicas: 1
  selector:
    matchLabels:
      app: my-db
  template:
    metadata:
      labels:
        app: my-db
    spec:
      containers:
        - name: db
          image: zaagm/my-workspace:bananes-export-db-latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pvc-db-volume
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - metadata:
        name: pvc-db-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1G
