version: '2'
services:
  app:
    container_name: app
    build:
      dockerfile: deploy/app/Dockerfile
    ports:
      - "8080:8080"
    environment:
      APP_ENV: dev
      DB_URL: jdbc:postgresql://db:5432/bananesexportdb
      DB_USERNAME: sa
      DB_PASSWORD: password
    depends_on:
      - db
  db:
    container_name: db
    build:
      dockerfile: deploy/db/Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
