version: '2'
services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    container_name: app
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      APP_ENV: dev
      DB_URL: jdbc:postgresql://db:5432/bananesexportdb
      DB_USERNAME: sa
      DB_PASSWORD: password
    depends_on:
      - db
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./script/entrypoint.sql:/docker-entrypoint-initdb.d/entrypoint.sql
