apiVersion: apps/v1
kind: Deployment
metadata:
  name:
    my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: app
          image: zaagm/my-workspace:bananes-export-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: "prd"
            - name: DB_URL
              value: "jdbc:postgresql://my-db-service:5432/bananesexportdb"
            - name: DB_USERNAME
              value: "sa"
            - name: DB_PASSWORD
              value: "password"
