apiVersion: apps/v1
kind: Deployment
metadata:
  name:
    my-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-lb
  template:
    metadata:
      labels:
        app: my-lb
    spec:
      containers:
        - name: lb
